# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

    global:
        CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

    matrix:
        - PYTHON_VERSION: "2.7"
        - PYTHON_VERSION: "3.5"
        - PYTHON_VERSION: "3.6"

matrix:
    fast_finish: true

install:
    # - "git clone git://github.com/astropy/ci-helpers.git"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "pip install tox"

# Not a .NET project, we build Astropy in the install step instead
build: false

test_script:
    - "tox"
